apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop-container
        image: naveen11122004/shop:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  type: NodePort
  selector:
    app: shop
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
